apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: judedba/vprofileapp:V1
        resources:
          limits:
            memory: "250Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: vproapp-port
     ## initContainers:
       # - name: init-mydb
       #   image: busybox
         # command: ['sh', '-c', 'until nslookup vprodb; echo waiting for mydb; sleep 2; done;']
        #- name: init-memcache
        #  image: busybox
         # command: ['sh', '-c', 'until nslookup vprocache01; echo waiting for memecached; sleep 2; done;']

--- 

apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  selector:
    app: vproapp
  ports:
  - port: 80
    targetPort: vproapp-port
    protocol: TCP
  type: LoadBalancer 

